site_name: Stochastic Finance Optimizer
site_description: A Python package for portfolio optimization using stochastic methods
site_author: Yuta Kondo
repo_url: https://github.com/Yuta-Kondo/stochastic_finance_optimizer
repo_name: Yuta-Kondo/stochastic_finance_optimizer

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'div'
      inline_tag: 'span'
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Documentation:
    - Installation: installation.md
    - Usage: usage.md
    - API Reference: api.md
    - Technical Report: technical_report.md
  - Examples:
    - Portfolio Optimization: examples/portfolio_optimization.md
  - Contributing: contributing.md 